name: ShippingReports
description: ''
version: 1.0.2
author: sparklearner123@gmail.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: shippingreports
  parentArtefactID: sparklearner123gmail.com_team
  buildSystem: wheel
  author: null
  createdAt: '2023-03-31 18:30:26'
  modifiedAt: '2023-03-31 18:30:26'
pipelines:
  pipelines/Pricing:
    name: Pricing
    description: creates a report summarizing prices, discounts, and shipping status
    author: sparklearner123@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-12-08 21:02:35'
    modifiedAt: '2023-04-06 06:42:37'
    datasets:
      inputs:
      - datasets/Shipments
      outputs:
      - datasets/PricingReport
    subgraphs: []
    dependencies: {}
  pipelines/PricingBySegment:
    name: ShippingBySegment
    description: Pricing for shipments configured per shipping segment
    author: sparklearner123@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-03-13 21:42:50'
    modifiedAt: '2023-04-24 15:35:33'
    datasets:
      inputs:
      - datasets/OrdersNCustomers
      - datasets/Shipments
      outputs:
      - datasets/Pricing
    subgraphs: []
    dependencies: {}
  pipelines/Retail:
    name: Retail
    description: ''
    author: sparklearner123@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-04-18 21:59:00'
    modifiedAt: '2023-04-18 22:10:25'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/nFfG9w8u_team_2155/nFfG9w8u_project_3246.git&subPath=&tag=HelloWorld/1.1.9&projectSubscriptionProjectId=3246&path=datasets/customers
      - gitUri=http://gitserver:3000/nFfG9w8u_team_2155/nFfG9w8u_project_3246.git&subPath=&tag=HelloWorld/1.1.9&projectSubscriptionProjectId=3246&path=datasets/orders
      outputs:
      - datasets/Report
    subgraphs:
    - subgraphs/DataCleanup
    dependencies: {}
datasets:
  datasets/Shipments:
    name: Shipments
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-08 21:05:07'
    modifiedAt: '2023-03-13 21:45:29'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: Warehouse
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-08 21:05:07'
        modifiedAt: '2022-12-08 21:05:07'
  datasets/report_shipment_prices:
    name: report_shipment_prices
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2022-12-08 21:12:16'
    modifiedAt: '2023-03-08 15:13:22'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: Database
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2022-12-08 21:12:16'
        modifiedAt: '2022-12-08 21:12:16'
  datasets/Orders_TPCH:
    name: Orders_TPCH
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-02-25 01:28:30'
    modifiedAt: '2023-02-25 01:28:30'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-02-25 01:28:30'
        modifiedAt: '2023-02-25 01:28:30'
  datasets/Customer_TPCH:
    name: Customer_TPCH
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-02-27 20:51:42'
    modifiedAt: '2023-03-06 17:01:45'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-02-27 20:51:42'
        modifiedAt: '2023-02-27 20:51:42'
  datasets/UnshippedOrders:
    name: UnshippedOrders
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-02 21:16:25'
    modifiedAt: '2023-03-03 21:09:04'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-02 21:16:25'
        modifiedAt: '2023-03-02 21:16:25'
  datasets/UnshippedOrdersEncoded:
    name: UnshippedOrdersEncoded
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-03 21:12:22'
    modifiedAt: '2023-03-03 22:15:00'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-03 21:12:22'
        modifiedAt: '2023-03-03 21:12:22'
  datasets/Unshipped:
    name: Unshipped
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-03 22:17:17'
    modifiedAt: '2023-03-03 22:19:09'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-03 22:17:17'
        modifiedAt: '2023-03-03 22:17:17'
  datasets/testconfig:
    name: testconfig
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-07 22:10:55'
    modifiedAt: '2023-03-08 14:55:48'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-07 22:10:55'
        modifiedAt: '2023-03-07 22:10:55'
  datasets/PricingReport:
    name: PricingReport
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-08 15:15:42'
    modifiedAt: '2023-03-17 20:50:44'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-08 15:15:42'
        modifiedAt: '2023-03-08 15:15:42'
  datasets/JoinedShippingData:
    name: JoinedShippingData
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-13 23:11:29'
    modifiedAt: '2023-03-16 18:58:41'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-13 23:11:29'
        modifiedAt: '2023-03-13 23:11:29'
  datasets/OrdersNCustomers:
    name: OrdersNCustomers
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-14 14:42:21'
    modifiedAt: '2023-03-14 14:42:21'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-14 14:42:21'
        modifiedAt: '2023-03-14 14:42:21'
  datasets/Pricing:
    name: Pricing
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-03-17 20:41:15'
    modifiedAt: '2023-03-23 19:31:47'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-03-17 20:41:15'
        modifiedAt: '2023-03-17 20:41:15'
  datasets/Report:
    name: Report
    description: ''
    author: sparklearner123@gmail.com
    createdAt: '2023-04-18 22:03:00'
    modifiedAt: '2023-04-18 22:03:00'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 990
        datasetType: File
        description: ''
        author: sparklearner123@gmail.com
        createdAt: '2023-04-18 22:03:00'
        modifiedAt: '2023-04-18 22:03:00'
templates: {}
jobs:
  jobs/WeeklyPricingReportPerVendor:
    name: WeeklyPricingReportPerVendor
    description: generates a weekly report specific to each retail vendor
    fabricUID: 990
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 ? * 3 *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/PricingBySegment
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2023-03-20 20:44:37'
    modifiedAt: '2023-03-22 21:44:56'
    author: sparklearner123@gmail.com
functions:
  author: null
  createdAt: '2023-03-31 18:30:26'
  modifiedAt: '2023-03-31 18:30:26'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/DataCleanup:
    name: DataCleanup
    description: ''
    author: sparklearner123@gmail.com
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-04-18 22:10:12'
    modifiedAt: '2023-04-18 22:10:12'
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies:
  '3246':
    projectUID: 3246
    projectName: HelloWorld
    repositoryPath: gitUri=http://gitserver:3000/nFfG9w8u_team_2155/nFfG9w8u_project_3246.git&subPath=
    version: HelloWorld/1.9.1
    author: null
    createdAt: '2023-04-24 15:29:37'
    modifiedAt: '2023-04-24 15:29:37'
pipelineConfigurations: {}
